[workspace]
members = ["src/kmr_api",
    "src/kmr_core",
    "src/kmr_ffi",
]

[workspace.dependencies]
thiserror = "2.0.18"
rstest = "0.26.1"
kmr_core = { path = "src/kmr_core" }
circular-buffer = "1.2.0"
derive_more = { version = "2.1.1", features = ["add", "mul"] }

[package]
name = "kmr_arch_v3"
version = "0.1.0"
edition = "2024"

[dependencies]
rstest.workspace = true
