//! The schedule module, designed to assign a schedule label to the critical,
//! modular systems (as per the definition of the ECS architecture).
//!
//! A system is simply a function injected in the KMR architecture via the
//! [`crate::robot::Robot`] builder pattern. These are used mainly for specifing
//! what happens during [`crate::runtime`]'s initialization and control phases.
//!
//! In a nutshell, the schedule module lets a label (`PreInit`, `Init`, …) be
//! assigned to a system (either a [`crate::controllers::Controller`] or a
//! [`crate::config`]), which allows the [`crate::runtime`] to know when to
//! call these systems.

// Generic params below reuse the snake_case bucket-field names as type-param
// idents (kept in lockstep by the `schedules!` macro), so allow the lint.
#![allow(non_camel_case_types)]

use frunk::{HCons, HNil};

mod macros;
use crate::controllers::Env;
use crate::sealed::Sealed;
use macros::schedules;

/// Sealed label trait. Users pick from the labels below; they can neither add a
/// phase nor forge one. The label *type* is the compile-time routing key that
/// picks a bucket in `Insert` — there is no runtime tag to dispatch on.
pub trait Schedule: Sealed + Copy {}

/// Appends `Node` to the *tail* of an `HList` bucket, preserving insertion
/// order (so controllers run in the order the user added them). Recursion on
/// the list shape: walk to the end, attach there. Purely type-level plumbing —
/// no heap, no `dyn`.
pub trait HAppend<Node> {
    type Output;
    fn append(self, node: Node) -> Self::Output;
}

impl<Node> HAppend<Node> for HNil {
    type Output = HCons<Node, HNil>;
    fn append(self, node: Node) -> Self::Output {
        HCons {
            head: node,
            tail: HNil,
        }
    }
}

impl<H, T: HAppend<Node>, Node> HAppend<Node> for HCons<H, T> {
    type Output = HCons<H, T::Output>;
    fn append(self, node: Node) -> Self::Output {
        HCons {
            head: self.head,
            tail: self.tail.append(node),
        }
    }
}

/// Routes `node` into the single bucket named by schedule label `S`, growing
/// that one bucket via [`HAppend`] and passing every other phase through
/// untouched. There is exactly one small impl per phase, generated by
/// `schedules!`: the label is the compile-time key that selects the field, so
/// routing is a static match with no runtime dispatch, index threading, or
/// re-sorting.
#[doc(hidden)]
pub trait Insert<S, Node> {
    type Output;
    fn insert(self, node: Node) -> Self::Output;
}

schedules! {
    pre_init         => PreInit,
    init             => Init,
    post_init        => PostInit,
    first            => First,
    each_tick        => EachTick,
    last             => Last,
}

/// Walks ONE schedule bucket — an `HList` of controller nodes — invoking each in
/// insertion order. `HNil` ends the walk; `HCons` runs its head then recurses on
/// the tail. The per-node leaf impls (the actual call) live in
/// [`crate::controllers`].
pub(crate) trait RunPhase {
    fn run_phase(&mut self, env: &mut Env<'_>);
}

impl RunPhase for HNil {
    fn run_phase(&mut self, _env: &mut Env<'_>) {}
}

impl<H: RunPhase, T: RunPhase> RunPhase for HCons<H, T> {
    fn run_phase(&mut self, env: &mut Env<'_>) {
        self.head.run_phase(env);
        self.tail.run_phase(env);
    }
}

#[cfg(test)]
mod tests {
    use super::{Drive, EachTick, First};
    use crate::robot::Robot;

    // The macro-generated `Drive` impl must be satisfied by a real, builder-grown
    // schedule — i.e. every bucket's node HList resolves `RunPhase`. Compile-level
    // guard: it never runs the loop.
    fn assert_drivable<CS: Drive>(_robot: &Robot<CS>) {}

    #[test]
    fn built_schedule_is_drivable() {
        let robot = Robot::new()
            .add_controller(First, |_t, _s, _se| {})
            .add_controller_with(EachTick, 0u32, |_t, _s, _se, n: &mut u32| *n += 1);
        assert_drivable(&robot);
    }
}
